name: 'Postpone Bot'
author: 'n01e0'
description: 'Create an issue for implementation that has been postponed with comments such as TODO or FIXME.'
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  config:
    description: 'config file'
    required: true
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/n01e0/ppb:latest'
  args:
    [
      '--token',
      '${{ inputs.token }}',
      '--config',
      '${{ inputs.config }}',
    ]
