name: 'Postpone Bot'
author: 'n01e0'
description: 'Create an issue for implementation that has been postponed with comments such as TODO or FIXME.'
inputs:
  organization:
    description: 'organization'
    required: true
  repository:
    description: 'repository'
    required: true
  token:
    description: 'GitHub token'
    required: true
  annotation_labels:
    description: 'annotation comment labels'
    required: false
    default: 'TODO,FIXME'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    [
      '--organization',
      '${{ inputs.organization }}',
      '--repository',
      '${{ inputs.repository }}',
      '--token',
      '${{ inputs.token }}',
      '--annotation-labels',
      '${{ inputs.annotation_labels }}',
    ]
