[package]
name = "ppb"
version = "0.1.0"
edition = "2021"
description = "postpone bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version="4.4.11", features=["derive"] }
grep = "0.3.1"
ignore = "0.4.21"
octocrab = "0.32.0"
rayon = "1.8.0"
serde = { version="1.0.193", features=["derive"] }
serde_yaml = "0.9.27"
thiserror = "1.0.50"
tokio = { version="1.35.0", features=["macros", "rt-multi-thread"] }
walkdir = "2.4.0"
