name: Postpone Bot
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  ppb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: n01e0/ppb@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: ./postpone.yml

